name: Publish docker
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registery
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: ghcr.io
          name: EvgenijHyva/NestJs-project/top-api
          username: ${{ github.actor }}
          password: ${{ secrets.NESTJS_GITHUB_TOKEN }}
          tags: "development"
  
